spring:
  cloud:
    gateway:
      routes:
        - id: video-service
          uri: http://video-service:8189
          predicates:
            - Path=/video-service/**
server:
  port: 8188
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG