spring:
  cloud:
    gateway:
      routes:
        - id: video-service
          uri: http://localhost:8189
          predicates:
            - Path=/video-service/**
        - id: client-service
          uri: http://localhost:8191
          predicates:
            - Path=/client-service/**
server:
  port: 8188
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG